services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0812
    ports:
      - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./db-init:/docker-entrypoint-initdb.d
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
